# Generated by Django 5.2.7 on 2025-12-29 17:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoffeeShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Roast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("tasting_notes", models.TextField()),
                ("is_seasonal", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "coffee_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roasts",
                        to="coffee_app.coffeeshop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrewEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Give your brew a short descriptive title",
                        max_length=100,
                    ),
                ),
                (
                    "brew_method",
                    models.CharField(
                        help_text="Espresso, pour over, French press, drip, aeropress, moka pot, etc.",
                        max_length=50,
                    ),
                ),
                ("entry", models.TextField(max_length=1000)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brew_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brew_entries",
                        to="coffee_app.roast",
                    ),
                ),
            ],
        ),
    ]
