# Generated by Django 5.2.7 on 2026-01-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brewentry",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AddField(
            model_name="brewentry",
            name="other_brew_method",
            field=models.CharField(
                blank=True,
                help_text="If 'Other', specify the brew method",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="brewentry",
            name="brew_method",
            field=models.CharField(
                choices=[
                    ("espresso", "Espresso"),
                    ("pour_over", "Pour Over"),
                    ("french_press", "French Press"),
                    ("drip", "Drip"),
                    ("aeropress", "AeroPress"),
                    ("moka_pot", "Moka Pot"),
                    ("other", "Other"),
                ],
                help_text="How did you brew this roast?",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="brewentry",
            name="entry",
            field=models.TextField(),
        ),
    ]
