# Generated by Django 5.2.7 on 2026-01-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coffee_app",
            "0002_alter_brewentry_options_brewentry_other_brew_method_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roast",
            name="profile",
            field=models.CharField(
                choices=[("light", "Light"), ("medium", "Medium"), ("dark", "Dark")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
