# Generated by Django 5.2.7 on 2026-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0003_roast_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="roast",
            name="crowd",
            field=models.CharField(
                choices=[
                    ("crowd-pleaser", "Crowd-pleaser"),
                    ("coffee enthusiast", "Coffee Enthusiast"),
                ],
                default="Coffee Enthusiast",
                max_length=20,
            ),
        ),
    ]
