# Generated by Django 5.2.7 on 2026-01-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0006_alter_brewentry_brew_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brewentry",
            name="brew_method",
            field=models.CharField(
                choices=[
                    ("espresso", "Espresso"),
                    ("pour_over", "Pour Over"),
                    ("french_press", "French Press"),
                    ("drip", "Drip"),
                    ("aeropress", "AeroPress"),
                    ("moka_pot", "Moka Pot"),
                    ("other", "Other"),
                ],
                help_text="How did you brew this roast?",
                max_length=50,
            ),
        ),
    ]
