# Generated by Django 5.2.7 on 2026-01-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0007_alter_brewentry_brew_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roast",
            name="crowd",
            field=models.CharField(
                choices=[
                    ("crowd-pleaser", "Crowd-pleaser"),
                    ("coffee enthusiast", "Coffee Enthusiast"),
                ],
                default="coffee enthusiast",
                max_length=20,
            ),
        ),
    ]
