# Generated by Django 5.2.7 on 2026-01-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0008_alter_roast_crowd"),
    ]

    operations = [
        migrations.AddField(
            model_name="roast",
            name="is_good_to_gift",
            field=models.BooleanField(default=False),
        ),
    ]
