# Generated by Django 5.2.7 on 2026-01-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0009_roast_is_good_to_gift"),
    ]

    operations = [
        migrations.AddField(
            model_name="roast",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
