# Generated by Django 5.2.7 on 2026-01-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0010_roast_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roast",
            name="is_featured",
        ),
    ]
