# Generated by Django 5.2.7 on 2026-01-14 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0011_remove_roast_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brewentry",
            name="entry",
            field=models.TextField(
                help_text="20–1000 characters",
                validators=[
                    django.core.validators.MinLengthValidator(20),
                    django.core.validators.MaxLengthValidator(1000),
                ],
            ),
        ),
    ]
