# Generated by Django 5.2.7 on 2026-01-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0013_alter_brewentry_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brewentry",
            name="other_brew_method",
        ),
    ]
