# Generated by Django 5.2.7 on 2026-01-17 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0014_remove_brewentry_other_brew_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brewentry",
            name="entry",
            field=models.TextField(
                help_text="5–1000 characters",
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="brewentry",
            name="title",
            field=models.CharField(
                help_text="Give your brew a short descriptive title", max_length=20
            ),
        ),
    ]
