# Generated by Django 5.2.7 on 2026-01-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0016_alter_brewentry_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brewentry",
            name="title",
            field=models.CharField(
                help_text="Give your brew a short descriptive title",
                max_length=25,
                unique=True,
            ),
        ),
    ]
