# Generated by Django 5.2.7 on 2026-01-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fav_brew",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="roast_preference",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
