# Generated by Django 5.2.7 on 2026-01-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0002_profile_fav_brew_profile_first_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Write a short bio to help others get to know you.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city_state",
            field=models.CharField(
                blank=True, help_text="(e.g. Austin, TX)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fav_brew",
            field=models.CharField(
                blank=True,
                help_text="(e.g. Drip, espresso, pour-over...)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_last_name",
            field=models.CharField(
                blank=True, help_text="Enter your first and last name.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="roast_preference",
            field=models.CharField(
                blank=True, help_text="Light, medium, or dark", max_length=50
            ),
        ),
    ]
