# Generated by Django 5.2.7 on 2026-01-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0003_alter_profile_bio_alter_profile_city_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fav_brew",
            field=models.CharField(
                blank=True,
                choices=[
                    ("espresso", "Espresso"),
                    ("pour_over", "Pour Over"),
                    ("french_press", "French Press"),
                    ("drip", "Drip"),
                    ("aeropress", "AeroPress"),
                    ("moka_pot", "Moka Pot"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="roast_preference",
            field=models.CharField(
                blank=True,
                choices=[("light", "Light"), ("medium", "Medium"), ("dark", "Dark")],
                max_length=50,
            ),
        ),
    ]
