# Generated by Django 5.2.7 on 2026-01-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0006_profile_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fav_brew",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Espresso", "Espresso"),
                    ("Pour Over", "Pour Over"),
                    ("French press", "French Press"),
                    ("Drip", "Drip"),
                    ("AeroPress", "AeroPress"),
                    ("Moka Pot", "Moka Pot"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_last_name",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
